const BLOCK_PROMPTS: Record<string, string> = {
  "hero-centered": "Modify headline text, subheadline text, and CTA button label only. Do not change layout, colours, or structure.",
  "hero-split": "Modify headline text, subheadline text, and CTA button label only. Do not change layout, image placement, or structure.",
  "hero-video-bg": "Modify headline text, subheadline text, and CTA button label only. Do not change video URL, layout, or structure.",
  "hero-minimal": "Modify headline text and CTA button label only. Do not change layout or structure.",
  "nav-standard": "Modify navigation link labels and logo alt text only. Do not add or remove links or change layout.",
  "nav-sticky": "Modify navigation link labels and logo alt text only. Do not add or remove links or change sticky behaviour.",
  "nav-minimal": "Modify navigation link labels and logo alt text only. Do not add or remove links or change layout.",
  "nav-mega": "Modify navigation link labels, group headings, and logo alt text only. Do not add or remove menu groups or change layout.",
  "content-text-image": "Modify heading text, body text, and image alt text only. Do not change layout, image source, or structure.",
  "content-text-only": "Modify heading text and body text only. Do not change layout or structure.",
  "content-columns-2": "Modify column heading text and body text only. Do not add or remove columns or change layout.",
  "content-columns-3": "Modify column heading text and body text only. Do not add or remove columns or change layout.",
  "content-accordion": "Modify accordion item titles and body text only. Do not add or remove items or change interaction behaviour.",
  "content-tabs": "Modify tab labels and tab body text only. Do not add or remove tabs or change interaction behaviour.",
  "content-timeline": "Modify timeline entry dates, titles, and descriptions only. Do not add or remove entries or change layout.",
  "media-gallery-grid": "Modify image alt text and captions only. Do not add or remove images, change grid columns, or modify layout.",
  "media-gallery-masonry": "Modify image alt text and captions only. Do not add or remove images, change columns, or modify layout.",
  "media-video-embed": "Modify video caption text only. Do not change the video URL, dimensions, or embed parameters.",
  "media-image-full": "Modify image alt text and caption only. Do not change the image source, dimensions, or layout.",
  "social-testimonials-grid": "Modify testimonial quote text, author name, and role only. Do not add or remove testimonials or change layout.",
  "social-testimonials-carousel": "Modify testimonial quote text, author name, and role only. Do not add or remove slides or change carousel behaviour.",
  "social-logos-strip": "Modify the heading text only. Do not add or remove logos or change layout.",
  "social-reviews-stars": "Modify review text and author name only. Do not change star ratings or add or remove reviews.",
  "social-case-study": "Modify case study title, client name, challenge, solution, and result text only. Do not change layout or structure.",
  "cta-banner-centered": "Modify headline text and CTA button label only. Do not change layout, colours, or structure.",
  "cta-banner-split": "Modify headline text, body text, and CTA button label only. Do not change layout or structure.",
  "cta-sticky-bar": "Modify bar text and CTA button label only. Do not change position, behaviour, or structure.",
  "form-contact": "Modify form title, field labels, and submit button text only. Do not add or remove form fields.",
  "form-newsletter": "Modify form title, placeholder text, and submit button text only. Do not add fields or change layout.",
  "form-booking": "Modify form title, field labels, and submit button text only. Do not add or remove form fields.",
  "pricing-table-2col": "Modify plan names, prices, and feature list text only. Do not add or remove plans or change layout.",
  "pricing-table-3col": "Modify plan names, prices, and feature list text only. Do not add or remove plans or change layout.",
  "pricing-toggle": "Modify plan names, prices, and feature list text only. Do not change toggle behaviour or add plans.",
  "team-grid": "Modify team member names, roles, and bio text only. Do not add or remove members or change layout.",
  "team-list": "Modify team member names, roles, and bio text only. Do not add or remove members or change layout.",
  "stats-counters": "Modify counter values and labels only. Do not add or remove counters or change animation behaviour.",
  "stats-bar-chart": "Modify bar labels and values only. Do not add or remove bars or change chart rendering.",
  "footer-standard": "Modify footer column headings, link labels, and copyright text only. Do not add or remove columns or change layout.",
  "footer-minimal": "Modify copyright text and link labels only. Do not add or remove links or change layout.",
  "footer-mega": "Modify column headings, link labels, social link labels, and copyright text only. Do not change layout or structure.",
  "utility-spacer": "Modify the height value only. Do not change the element type or add content.",
  "utility-divider": "Modify the divider style and colour only. Do not change the element type or add content.",
  "utility-custom-code": "Modify the HTML, CSS, and JS content only. Do not change the container or sandbox restrictions.",
  "utility-embed": "Set the iframe src URL only. Do not modify dimensions or sandbox attributes.",
};

export function getPrompt(blockId: string): string {
  return BLOCK_PROMPTS[blockId] ?? "Modify text content only. Do not change layout, structure, or styling.";
}

export { BLOCK_PROMPTS };
