import { pgTable, varchar, timestamp, uniqueIndex } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
import { sql } from "drizzle-orm";

export const PLAN_TIERS = {
  solo: {
    id: "solo",
    name: "Solo",
    price: 99,
    tagline: "Stop paying for 6 tools. Pay for one.",
    trialDays: 14,
    trialPrice: 1,
    maxWorkspaces: 1,
    maxUsers: 1,
    maxDomains: 1,
    aiPostsPerWorkspacePerMonth: 40,
    googleIndexingAutomation: true,
    rankTrackerKeywords: 1000,
    contentEngine: true,
    rankTracker: true,
    localSearchGrid: true,
    googleSearchConsole: true,
    crmPipeline: true,
    twilioSmsVoice: true,
    websiteWidget: true,
    cmsIntegration: true,
    linkBuilder: true,
    postValidator: true,
    onPageAuditor: true,
    siteProfiler: true,
    schemaMarkup: true,
    invoicing: true,
    linkHealth: true,
    byok: true,
    multiLanguage: true,
    customDomain: true,
    bulkCampaigns: true,
    contentModeration: true,
    whiteLabel: false,
    teamRoles: false,
    apiAccess: false,
    ssoSaml: false,
    resellerLicence: false,
    prioritySupport: false,
    dedicatedAccountManager: false,
    priorityOnboarding: false,
  },
  pro: {
    id: "pro",
    name: "Pro",
    price: 199,
    tagline: "Turn your SEO service into a product.",
    trialDays: 30,
    trialPrice: 0,
    maxWorkspaces: 25,
    maxUsers: 5,
    maxDomains: 25,
    aiPostsPerWorkspacePerMonth: 40,
    googleIndexingAutomation: true,
    rankTrackerKeywords: 1000,
    contentEngine: true,
    rankTracker: true,
    localSearchGrid: true,
    googleSearchConsole: true,
    crmPipeline: true,
    twilioSmsVoice: true,
    websiteWidget: true,
    cmsIntegration: true,
    linkBuilder: true,
    postValidator: true,
    onPageAuditor: true,
    siteProfiler: true,
    schemaMarkup: true,
    invoicing: true,
    linkHealth: true,
    byok: true,
    multiLanguage: true,
    customDomain: true,
    bulkCampaigns: true,
    contentModeration: true,
    whiteLabel: true,
    teamRoles: true,
    apiAccess: false,
    ssoSaml: false,
    resellerLicence: true,
    prioritySupport: true,
    dedicatedAccountManager: false,
    priorityOnboarding: false,
  },
  agency: {
    id: "agency",
    name: "Agency",
    price: 349,
    tagline: "Infrastructure for agencies that mean business.",
    trialDays: 30,
    trialPrice: 0,
    maxWorkspaces: 50,
    maxUsers: 10,
    maxDomains: 50,
    aiPostsPerWorkspacePerMonth: 40,
    googleIndexingAutomation: true,
    rankTrackerKeywords: 1000,
    contentEngine: true,
    rankTracker: true,
    localSearchGrid: true,
    googleSearchConsole: true,
    crmPipeline: true,
    twilioSmsVoice: true,
    websiteWidget: true,
    cmsIntegration: true,
    linkBuilder: true,
    postValidator: true,
    onPageAuditor: true,
    siteProfiler: true,
    schemaMarkup: true,
    invoicing: true,
    linkHealth: true,
    byok: true,
    multiLanguage: true,
    customDomain: true,
    bulkCampaigns: true,
    contentModeration: true,
    whiteLabel: true,
    teamRoles: true,
    apiAccess: true,
    ssoSaml: false,
    resellerLicence: true,
    prioritySupport: true,
    dedicatedAccountManager: true,
    priorityOnboarding: true,
  },
  enterprise: {
    id: "enterprise",
    name: "Enterprise",
    price: 999,
    tagline: "You've outgrown tools. You need infrastructure.",
    trialDays: 0,
    trialPrice: 0,
    maxWorkspaces: Infinity,
    maxUsers: 20,
    maxDomains: Infinity,
    aiPostsPerWorkspacePerMonth: 40,
    googleIndexingAutomation: true,
    rankTrackerKeywords: 1000,
    contentEngine: true,
    rankTracker: true,
    localSearchGrid: true,
    googleSearchConsole: true,
    crmPipeline: true,
    twilioSmsVoice: true,
    websiteWidget: true,
    cmsIntegration: true,
    linkBuilder: true,
    postValidator: true,
    onPageAuditor: true,
    siteProfiler: true,
    schemaMarkup: true,
    invoicing: true,
    linkHealth: true,
    byok: true,
    multiLanguage: true,
    customDomain: true,
    bulkCampaigns: true,
    contentModeration: true,
    whiteLabel: true,
    teamRoles: true,
    apiAccess: true,
    ssoSaml: true,
    resellerLicence: true,
    prioritySupport: true,
    dedicatedAccountManager: true,
    priorityOnboarding: true,
  },
} as const;

export type PlanTierId = keyof typeof PLAN_TIERS;

export function getPlanTier(planId: string) {
  return PLAN_TIERS[planId as PlanTierId] || PLAN_TIERS.solo;
}

export const users = pgTable(
  "users",
  {
    id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
    email: varchar("email"),
    firstName: varchar("first_name"),
    lastName: varchar("last_name"),
    profileImageUrl: varchar("profile_image_url"),
    plan: varchar("plan", { length: 50 }).notNull().default("solo"),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
  },
  (t) => [
    uniqueIndex("users_email_unique").on(t.email),
  ]
);

export const insertUserSchema = createInsertSchema(users).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

export type UpsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;
