name: Auto Deploy to Production
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [client-publish]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to production
        run: |
          git push origin HEAD:production --force
